### ISSUE TITLE
the /perk command needs a permission?

### ISSUE THREAD

**Issue by Uharn** [Fabilucius/advanced-perks#24]
Thanks for updating your plugin: 
/perks - (permission: none)
This command will open the perk gui for the player that used this command.

i cannot find out what permission is needed for that command, non OP players gets a "not enought permission" error

**Comment by Fabilucius** [comment]
Will Push a hotfix today

**Comment by Fabilucius** [comment]
My Bad

**Comment by Fabilucius** [comment]
Fixed the bug with c6bc9f1
