### ISSUE TITLE
advancedperks.maxperks. is not taken in account

### ISSUE THREAD

**Issue by Uharn** [Fabilucius/advanced-perks#27]
https://github.com/Fabilucius/advanced-perks/issues/25 is not fixed for me:

Here is my permission setup:
 I have some ranks that cumulate themselves
 guest: advancedperks.maxperks.0
minivip: advancedperks.maxperks.1
vip: advancedperks.maxperks.2
vipgold: advancedperks.maxperks.4

So a vipgold has:
 advancedperks.maxperks.0 = true
 advancedperks.maxperks.1 = true
 advancedperks.maxperks.2 = true
 advancedperks.maxperks.4 = true
 
 it should be allowed to get only 4 simultaneous perks but it get unlimited numbers of activated perks at the same time

**Comment by Fabilucius** [comment]
How many Max-Perks have you set in your configuration?

**Comment by Uharn** [comment]
6 (and only that limits applies instead of maxperks)

**Comment by Fabilucius** [comment]
Than your global Limit is 6 the permission only overwrites when its higher than Global Maxperk from configuration

**Comment by Uharn** [comment]
it works thanks
